### ISSUE TITLE
Debes cambiar el autor

### ISSUE THREAD

**Issue by rdp89** [Vsevillano/Pr-ctica_Issue#1]
https://github.com/Vsevillano/Practica_Issue/blob/master/concesionario2/estructura/Coche.java#L37

**Comment by Vsevillano** [comment]
Gracias Rafa, la verdad que con las prisas se me habia olvidado, se lo comentare a @lmagarin

**Comment by rdp89** [comment]
Perfecto, me alegra ayudarte con estos despistes, un saludo!
